name: "MyTube Dash"
version: "1.0.3"
slug: "mytubedash"
description: "Dashboard personal pentru vizionarea clipurilor YouTube fără algoritmi."
arch:
  - amd64
  - aarch64
startup: application
boot: auto
ingress: true
ingress_port: 3000
panel_icon: mdi:youtube
panel_title: "MyTube Dash"
